spring.config.activate.on-profile=local
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:shopwave_rework}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
